feat: support enable kubelet service

diff --git a/core b/core
--- a/core
+++ b/core
@@ -92,6 +92,30 @@ install() {
   log::info "[$(timestamp)][package][$name] installing ..."
   os::install $source_bin_file $usr_bin_dir $name
 
+  # reference:
+  #   - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
+  if [ "$(os::has_command systemctl)" = "true" ]; then
+    # install service
+    local systemd_service_dir=/etc/systemd/system
+    local systemd_service_config=$systemd_service_dir/kubelet.service
+    if [ ! -f "$systemd_service_config" ]; then
+      if [ ! -d "$systemd_service_dir" ]; then
+        sudo mkdir -p $systemd_service_dir
+      fi
+
+      log::info "[$(timestamp)][package][$name] install service to $systemd_service_config ..."
+      sudo cp $PACKAGE_DIR/etc/systemd/system/kubelet.service $systemd_service_config \
+        && sudo systemctl daemon-reload \
+        && sudo systemctl enable kubelet
+      if [ "$?" != "0" ]; then
+        log::error "[$(timestamp)][package][$name] failed to start containerd service with systemd."
+        return 1
+      fi
+
+      log::success "[$(timestamp)][package][$name] installed service to $systemd_service_config ."
+    fi
+  fi
+
   if [ "$PLUGIN_PACKAGE_INSTALL_MODE" != "test" ]; then
     # clean
     log::info "[$(timestamp)][package][$name] cleaning ..."
